# Terminal configuration. Noctalia manages the included theme.
[main]
font=JetBrainsMono Nerd Font Mono:size=12
font-bold=JetBrainsMono Nerd Font Mono:size=12
font-italic=JetBrainsMono Nerd Font Mono:size=12
pad=8x8
selection-target=both
include=~/.config/foot/themes/noctalia

[scrollback]
lines=10000

[csd]
preferred=none
size=0

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[mouse-bindings]
selection-override-modifiers=Shift

clipboard-copy=BTN_RIGHT
clipboard-paste=BTN_MIDDLE
primary-paste=none
select-extend=Alt+BTN_RIGHT
select-extend-character-wise=Control+BTN_RIGHT
